let accessToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9FWTJSVGM1UlVOR05qSXhSRUV5TURJNFFUWXdNekZETWtReU1EQXdSVUV4UVVRM05EazFNQSJ9.eyJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiXSwieC1oYXN1cmEtdXNlci1pZCI6ImF1dGgwfDVlYTA0Y2NiNzliNjRlMGNmNDA1M2U5MSJ9LCJuaWNrbmFtZSI6ImduYW5ha2FudGhpIiwibmFtZSI6ImduYW5ha2FudGhpQGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3MuZ3JhdmF0YXIuY29tL2F2YXRhci83OTA4Zjg3NmU2OGUwN2IxNjU3MjY2N2UwYTEwZDY2NT9zPTQ4MCZyPXBnJmQ9aHR0cHMlM0ElMkYlMkZjZG4uYXV0aDAuY29tJTJGYXZhdGFycyUyRmduLnBuZyIsInVwZGF0ZWRfYXQiOiIyMDIwLTA0LTIyVDEzOjU1OjI0LjU1N1oiLCJpc3MiOiJodHRwczovL2dyYXBocWwtdHV0b3JpYWxzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZWEwNGNjYjc5YjY0ZTBjZjQwNTNlOTEiLCJhdWQiOiJQMzhxbkZvMWxGQVFKcnprdW4tLXdFenFsalZOR2NXVyIsImlhdCI6MTU4NzU2MzcyNiwiZXhwIjoxNTg3NTk5NzI2LCJhdF9oYXNoIjoiTVI2VU1QNXNzeXdMZFJTbF9lTHhpZyIsIm5vbmNlIjoiNGc5QzRsQXFlNjdPYWtUTmNwdjlnekpUUm1QUjFFfkUifQ.TAjcdBOFgFaexyExXyl_t9AKGJgJE9R_aMt_IvFQ-5yuP2V9AcOxdOwtP8Nu94sRk2mIy1UMyBGqx6PjMXxN2pVDk3r_oUn8loOTv9lbe8gd6GvqHinSlevVcfOeTm50Ol40py51dpOv_egEmaATArC9MS6etkk7OLaGO86laUeV_o4GPVfOYKk8x_bMWTI6mi6nDc0f1U6w8myFGRTNoD4r2I_XSpJLAWwHiB1HQks1yscLrHDEwgNo9kdYk1Sju0zPaGGjvYe_CXRHqRP1hdKrjPtM2-WfWy07WfwDgAItoC-O1mgrHqPjS6KABuWb_ppnxh_R98n6uH1PwsHmuA";

let query = `query {
  online_users {
    id
  }
}`;

let headers = {
 'Authorization': `Bearer ${accessToken}`,
 "Content-Type": "application/json"
};

let res = http.post("https://hasura.io/learn/graphql",
 JSON.stringify({ query: query }),
 {headers: headers}
);

